[{
    "urlFrase": "https://y.yarn.co/72eec69d-4f8d-4720-884e-0d861a7a309f.mp4",
    "frase": "We were some team, huh?",
    "fraseTranslate": "Éramos uma equipe, hein?",
    "wordTranslate": "We were : Nós éramos, some team : alguma equipe, huh? : hein?",
    "voiceTranslate": "",
    "pronuncia": "we wer{e} s[o´a`]m{e} t[e´i`]{a}m, {h}[u´ã`]h?",
    "voicePronuncia": "",
    "exemploFrase": "Yeah, we were some trio.",
    "exemploTranslate": "Sim, nós éramos um/algum trio.",
    "urlExemplo": "https://y.yarn.co/57a9c54e-e56a-4d3c-b111-44a9c70daa4f.mp4"
}, {
    "urlFrase": "https://y.yarn.co/358b2d41-822e-4b43-9f8f-770604214e01.mp4",
    "frase": "Were? Come on. We're still a team.",
    "fraseTranslate": "Éramos? Vamos. Somos ainda uma equipe.",
    "wordTranslate": "Were? : Éramos?, Come on : Vamos, We're / We are : Nós Somos, still : ainda, A team : um time",
    "voiceTranslate": "",
    "pronuncia": "w{e}r[e´â`]? (com{e} on). w{e}'re stil(l a) t[e´i`]{a}m.",
    "voicePronuncia": "",
    "exemploFrase": "Come on, we're a team. ",
    "exemploTranslate": "Vamos, somos uma equipe.",
    "urlExemplo": "https://y.yarn.co/05e34795-2455-4ed1-b6f1-ca3af4eb6033.mp4"
}, {
    "urlFrase": "https://y.yarn.co/82a2b4e0-bd2b-4051-93a4-e2827d78a429.mp4",
    "frase": "I'm sorry I set you up.",
    "fraseTranslate": "Lamento ter armado para você.",
    "wordTranslate": "I'm sorry : eu lamento / me desculpa, I set you up : Eu armei você",
    "voiceTranslate": "",
    "pronuncia": "i'm sorr(y i) se(t you) [u´a`]{p}.",
    "voicePronuncia": "",
    "exemploFrase": "-You set me up. -Oh, yeah, I set you up. Of course",
    "exemploTranslate": "-Você armou para mim. -Ah, sim, eu armei para você. Claro",
    "urlExemplo": "https://y.yarn.co/9dc5ca11-f1b0-45d8-8e21-f1bcc90f76d4.mp4"
}, {
    "urlFrase": "https://y.yarn.co/da225db9-29f8-497e-8b9e-b06d493b6fba.mp4",
    "frase": "Ah. You know me. I'm too lazy to hold a grudge.",
    "fraseTranslate": "Ah. Você me conhece. Eu sou muito preguiçoso para guardar um rancor.",
    "wordTranslate": "You know me : Você me conhece,  I'm too lazy: eu sou muito preguiçoso, to hold: guardar / segurar, a grudge : um rancor",
    "voiceTranslate": "",
    "pronuncia": "ah. you {k}now me. i'm t[oo´u`] l[a´êi`]zy to hol(d a) gr[u´a`]d[g´j`]e.",
    "voicePronuncia": "",
    "exemploFrase": "I'm not one to hold a grudge. ",
    "exemploTranslate": "Não sou de guardar rancor.",
    "urlExemplo": "https://y.yarn.co/ce9ba7ed-f2fd-435c-a239-cf6651d660c5.mp4"
}, {
    "urlFrase": "https://y.yarn.co/3e4193a5-4dc9-479e-8c62-0d434a92e565.mp4",
    "frase": "Hey. Knock it off. squirt.",
    "fraseTranslate": "Ei. Pare com isso. esguicho.",
    "wordTranslate": "hey : ei, Knock it off : Pare com isso, squirt: esguicho",
    "voiceTranslate": "",
    "pronuncia": "hey. {k}no(ck i[t´r`] off). squirt.",
    "voicePronuncia": "",
    "exemploFrase": "Eww! Knock it off!",
    "exemploTranslate": "Eca! Pare com isso!",
    "urlExemplo": "https://y.yarn.co/7588e1af-69d7-48f3-9ec9-273086719b28.mp4"
}, {
    "urlFrase": "https://y.yarn.co/7d0c6424-7e3b-4c2c-8cce-f2ddf81dfe12.mp4",
    "frase": "You have to be strong.",
    "fraseTranslate": "Você tem que ser forte.",
    "wordTranslate": "You : você, have to : tem que,  be : ser, strong : forte",
    "voiceTranslate": "",
    "pronuncia": "you (h[a´e`]{ve} [t´r`][o´â`]) be stron{g}.",
    "voicePronuncia": "",
    "exemploFrase": "You have to be strong. ",
    "exemploTranslate": "Você tem que ser forte.",
    "urlExemplo": "https://y.yarn.co/83e05af2-2c91-4b10-962f-78068ac6b30e.mp4"
}, {
    "urlFrase": "https://y.yarn.co/d876fc5f-01a0-430f-9eb3-b9be31213820.mp4",
    "frase": "You have to take care of Manfred and Sid.",
    "fraseTranslate": "Você tem que cuidar de Manfred e Sid.",
    "wordTranslate": "You : você, have to : tem que, take care : cuidar, of Manfred and Sid : de Manfred e Sid",
    "voiceTranslate": "",
    "pronuncia": "you have (to take care o[f´v`]) Manfred (an{d} Sid.)",
    "voicePronuncia": "",
    "exemploFrase": "Just have to take care of yourself. Take care of myself? ",
    "exemploTranslate": "Só tem que se cuidar. Cuidar de mim mesmo?",
    "urlExemplo": "https://y.yarn.co/006ad54f-a8f5-41a1-aa36-778555a45ebd.mp4"
}, {
    "urlFrase": "https://y.yarn.co/e43524eb-70f9-48dc-8710-4364790ec533.mp4",
    "frase": "Especially Sid.",
    "fraseTranslate": "Especialmente Sid.",
    "wordTranslate": "Especially : Especialmente / Principalmente ",
    "voiceTranslate": "",
    "pronuncia": "espe[cia´shâ`]lly sid.",
    "voicePronuncia": "",
    "exemploFrase": "Not especially.",
    "exemploTranslate": "Nada de especial.",
    "urlExemplo": "https://y.yarn.co/75cb1390-d4a7-4331-b0c8-bf0dd38a5f4d.mp4"
}, {
    "urlFrase": "https://y.yarn.co/d940b15d-ff73-41fa-a296-0e1afa8386a5.mp4",
    "frase": "Come on. You can lick this. You're a tiger. Look I'll carry you. Come on, what do you say?",
    "fraseTranslate": "Qual é. Você pode lamber isso. Você é um tigre. Olha eu vou te carregar. Vamos, o que você me diz?",
    "wordTranslate": "Come on : qual é / vamos, You can : Você pode, lick this : lamber isso, You're a tiger : você é um tigre, Look : olhe, i'll / i will : eu vou, carry you : carregar você, whats do you say : o que você diz",
    "voiceTranslate": "",
    "pronuncia": "(com{e} on). you c[a´e`]n lick this. you'(r{e} a) tiger. look (i'll carry you), (wha[t´r`] {do} you) s[a´e`]y?",
    "voicePronuncia": "",
    "exemploFrase": "- Come on, what do you say? - Come on. ",
    "exemploTranslate": "- Vamos, o que você diz? - Vamos.",
    "urlExemplo": "https://y.yarn.co/cafb7105-e9a2-4f7d-a39d-ac52ff9f413f.mp4"
}, {
    "urlFrase": "https://y.yarn.co/63f6e879-0cf4-4ce9-b112-1308e9caa7b8.mp4",
    "frase": "Tell him he's going to be OK, Manny.",
    "fraseTranslate": "Diga que ele vai estar bem, Manny.",
    "wordTranslate": "Tell him : Diga a ele, he's going : ele vai, to be ok : estar bem",
    "voiceTranslate": "",
    "pronuncia": "tel(l {h}im) he's goin{g} to be ok, Manny.",
    "voicePronuncia": "",
    "exemploFrase": "He's going to be OK. ",
    "exemploTranslate": "Ele vai ficar bem.",
    "urlExemplo": "https://y.yarn.co/bd24057c-8db6-4c95-9665-6be0c494b833.mp4"
}, {
    "urlFrase": "https://y.yarn.co/faf268c5-3041-4e7f-b909-df0faf070923.mp4",
    "frase": "Listen. You have to leave me here.",
    "fraseTranslate": "Ouça. Você tem que me deixar aqui.",
    "wordTranslate": "Listen: ouça, You have to : você tem que, leave me : me deixar, here: aqui",
    "voiceTranslate": "",
    "pronuncia": "lis{t}en. you have to l[ea´i`]ve me here.",
    "voicePronuncia": "",
    "exemploFrase": "Listen, you can't leave me here. ",
    "exemploTranslate": "Ouça, você não pode me deixar aqui.",
    "urlExemplo": "https://y.yarn.co/ecf1df98-5e4f-48c8-ae54-a84f30eedf46.mp4"
}, {
    "urlFrase": "https://y.yarn.co/26ca0082-8dd4-473a-8ce0-cbde0c6fc291.mp4",
    "frase": "If those humans get through the pass, you'll never catch them.",
    "fraseTranslate": "Se aqueles humanos atravessarem a passagem, vocês nunca os pegará.",
    "wordTranslate": "If those: Se aqueles, humans : humanos, get through : atravessar, the pass : A passagem, you'll never : vocês nunca,  catch them : os pegará.",
    "voiceTranslate": "",
    "pronuncia": "if those {h}umans (ge{t} through) the pass, you'll never catch them.",
    "voicePronuncia": "",
    "exemploFrase": "You'll never catch them. ",
    "exemploTranslate": "Você nunca os pegará.",
    "urlExemplo": "https://y.yarn.co/e0835dc7-eba2-432c-a102-5b0f9ea990f0.mp4"
}, {
    "urlFrase": "https://y.yarn.co/617c6130-8b0e-44ba-a13e-206573204c76.mp4",
    "frase": "You didn't have to do that.",
    "fraseTranslate": "Você não precisava fazer isso.",
    "wordTranslate": "You : você, didn't have : não precisava, to do : fazer, that : isso",
    "voiceTranslate": "",
    "pronuncia": "you di[d´r`]n{'t} have (to do) that.",
    "voicePronuncia": "",
    "exemploFrase": "You didn't have to do that. ",
    "exemploTranslate": "Você não precisava fazer isso.",
    "urlExemplo": "https://y.yarn.co/30eea737-872d-4e5d-8936-203d6b35b86d.mp4"
}, {
    "urlFrase": "https://y.yarn.co/df0d94d1-d5b3-4528-ba30-7cd87b3cf76a.mp4",
    "frase": "That's what you do in a herd.",
    "fraseTranslate": "Isso é o que você faz em um rebanho.",
    "wordTranslate": "That's / that is : isso é, what you do : o que você faz, in a herd : em um rebanho",
    "voiceTranslate": "",
    "pronuncia": "th[a´e`]t's (what you) do i(n a) herd.",
    "voicePronuncia": "",
    "exemploFrase": "Because that's what you do.",
    "exemploTranslate": "Porque é isso que você faz.",
    "urlExemplo": "https://y.yarn.co/66a152b4-1180-416e-b6d8-7283fb02363a.mp4"
}]